### ISSUE TITLE
How to change wallet password

### ISSUE THREAD

**Issue by garyyu** [gottstech/grin-wallet#27]
Currently, there's no way to change the wallet password. User have to remove the whole wallet and recover from mnemonic phrases, to get a chance to use a new password.

Same requirement also for wallet owner_api.

[Updated 5th July]
It's a bad idea to support changing password via owner_api, we only need the command line and the API for libs.

**Comment by terryzhao** [comment]
Support change wallet password both in commandline and JSON-RPC.

**CommandLine:**
- grin-wallet passupdate

**rest api:**
- curl -0 -XPOST http://127.0.0.1:13420/v2/owner -d @pass_update.json 
- pass_update.json:
{
		"jsonrpc": "2.0",
		"method": "pass_update",
		"params": ["123456"],
		"id": 1
}

**Comment by garyyu** [comment]
Update:  `change_password` `owner_api` interface has been removed. it doesn't make sense to transmit password via network, even on localhost.

**Comment by garyyu** [comment]
closed by #29
