### ISSUE TITLE
Latest master fails to build with rust 1.38.0

### ISSUE THREAD

**Issue by terryzhao** [gottstech/grin-wallet#63]
Following upgrade from rust 1.37.0 to 1.38.0, latest master fails to build with the following error and lots of warnings:

error: proc-macro derive panicked
  --> /home/terry/.cargo/registry/src/github.com-1ecc6299db9ec823/grin_secp256k1zkp-0.7.7/src/key.rs:32:10
   |
32 | #[derive(Zeroize)]
   |          ^^^^^^^
   |
   = help: message: unknown zeroize attribute: (drop)

error: aborting due to previous error

The following warnings were emitted during compilation:

**Comment by garyyu** [comment]
Fixed by https://github.com/gottstech/grin-wallet/pull/64
